### ISSUE TITLE
pyenv install fails at download stage

### ISSUE THREAD

**Issue by marchoeppner** [yyuu/pyenv-installer#17]
Hi,

been trying to get pyenv to work on a Scientific Linux 6.5 system. I had this working on an earlier kernel/cluster setup but in the current constellation of kernel etc pyenv won't work. I used the pyenv-installer script (but also tried cloning directly from github) and set the environment variables. When running pyenv install 2.7.8, I get:

pyenv install 2.7.8
Downloading Python-2.7.8.tgz...
-> https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz
error: failed to download Python-2.7.8.tgz

BUILD FAILED (Scientific 6.5 using python-build 20141211-6-g995da2d)

I can download this file manually following above link, so that doesn't seem to be the issue. I don't have the versions folder to which I am guessing the download will go. I also have no shims folder, by the way. Running the make file in the pyenv root throws one error about shims directory not being writeable (which makes sense, since it doesn't exist). There is no mentioning of a compilation step in the instructions, so I am guessing something is amiss here?

**Comment by yyuu** [comment]
The [pyenv-installer](https://github.com/yyuu/pyenv-installer/blob/ee94cf53884c0d5edc1576bc52776bfdc3676892/bin/pyenv-installer) is just a single file shell script to clone pyenv from GitHub repo to local machine. It doesn't configure nothing to your shell. Here isn't right place to report the issue.

By default, `pyenv install` (== `python-build`) tries to download python archives from https://yyuu.github.io/pythons/ if it is available. Please check if you can download https://yyuu.github.io/pythons/74d70b914da4487aa1d97222b29e9554d042f825f26cb2b93abd20fdda56b557 and unset `PYTHON_BUILD_SKIP_MIRROR` if you cannot download it from the mirror (you're in behind some firewall?).

https://github.com/yyuu/pyenv/blob/995da2df89ea0de6717c9a13ec9715238dc5b5c8/plugins/python-build/bin/python-build#L1670
