### ISSUE TITLE
Load pyenv automatically without ~/.bash_profile

### ISSUE THREAD

**Issue by Nairolf21** [yyuu/pyenv-installer#18]
Hi, 
I'm trying to install pyenv. I've done this command curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
Then after what I should do in order to load pyenv automatically ? Because I'm using Xubuntu 14.04 and I don't have any ~/.bash_profile (but I have ~/.profile). 
Should I add it to ~/.profile ? 

Thanks

**Comment by bucaran** [comment]
You are using `bash` right? When bash is invoked as an interactive login shell, or as a non-interactive shell with the `--login` option, it first reads and executes commands from the file `/etc/profile`, if it exists. 

After reading that, it looks for `~/.bash_profile`, `~/.bash_login`, and `~/.profile`, in that order, and reads and __executes__ commands from the _first one that exists_. 

So, you may want to use `~/.profile` if you use other shells such as `zsh`, or create a `/.bash_profile` and add it there if you just use `bash`.

I would add it to `~/.profile`.

**Comment by yyuu** [comment]
`~/.bash_profile` would be the best place to put bash only configuration. See bash(1).

**Comment by bucaran** [comment]
@Nairolf21 In case the comment above doesn't make sense, `bash(1)` refers to the man page for `bash`. Just type `man bash` in your console.
