### ISSUE TITLE
User can set $profile by himself?

### ISSUE THREAD

**Issue by hengyunabc** [yyuu/pyenv-installer#19]
I found that under some verion centos, ubuntu，pyenv-installer cant not detect profile correct.

User can set $profile by himself?

Lkie this:
```bash
wget https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
chmod +x pyenv-installer
profile="~/.bash_profile"  ./pyenv-installer
```

**Comment by yyuu** [comment]
It's just a message based on shell type. For bash, it'll display the shell configuration file as `~/.bash_profile` and I cannot imagine how useful this change is.
