### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by Yasumoto** [yyuu/pyenv-installer#20]
`pyenv` looks awesome! We've been recommending a script called [bootstrap_python.sh](https://github.com/wickman/python-bootstrap/blob/master/bootstrap_python.sh) for a few years now, but `pyenv` definitely looks like a much better solution.

Is there any chance we can cut a version of `pyenv-installer`? I'd much prefer we point to a released tag of the install script in a (much simpler) `bootstrap_python.sh` if possible.

Thanks!

**Comment by yyuu** [comment]
I agree that this repo should be tagged. I will do it later.

**Comment by yyuu** [comment]
Created release tag v20150113.
