### ISSUE TITLE
Ignoring potentially dangerous file name ../Python-2.7.8/Lib/site.py

### ISSUE THREAD

**Issue by robnagler** [yyuu/pyenv-installer#22]
The patches in python-builder have relative path names (begin with '..'), which `patch` doesn't like. 

I worked around the issue with this:

```bash
perl -pi -e 's{^(\+\+\+|--- |diff.* )\.\./}{$1}' $(find ~/.pyenv -name \*.patch)
```

However, a better solution would be to generate the patches without relative path names.

**Comment by yyuu** [comment]
This is not an issue of `pyenv-installer`.
