### ISSUE TITLE
Allow to clone with depth of 1

### ISSUE THREAD

**Issue by thedrow** [yyuu/pyenv-installer#34]
This should speed up installation of pyenv by a lot since you don't need to download the entire index.

**Comment by tejasmanohar** [comment]
+1

**Comment by alexjurkiewicz** [comment]
Does the installer need to clone at all? Downloading a tar.gz of the HEAD release from github would be even faster, but I'm not sure if pyenv needs the git structure for some purpose...

**Comment by yyuu** [comment]
pyenv itself isn't depending on Git's repository structure. Though it's useful to install it as a Git repository to make it easy to pull new changes after the installation.
