### ISSUE TITLE
pyenv update to specific version?

### ISSUE THREAD

**Issue by teohhanhui** [yyuu/pyenv-installer#37]
Update to specific version, or latest stable version...

**Comment by obestwalter** [comment]
@teohhanhui sorry for not getting back to you. This might be too late but I'll answer anyway and close this then :)

AFAICT pyenv-update is not really prepared to do that yet, but as it is only a thin wrapper arpund git you could do:

    $ cd $HOME/.pyenv  # or wherever you installed it
    $ git fetch --tags
    $ git checkout v1.0.5  # or any other tag found at https://github.com/yyuu/pyenv/releases

You might have to do that for some of the related repos in `$HOME/.pyenv` as well, in case they break compatibility though ...
