### ISSUE TITLE
error message in first install

### ISSUE THREAD

**Issue by ysolis** [yyuu/pyenv-installer#45]
I was installing pyenv in a new laptop, and do a new install with pyenv-installer.

all was good, but I have an error message that didn't appear in previous installs.

 ```
~  pyenv update
Updating /home/yonsy/.pyenv...
pyenv-update: /home/yonsy/.pyenv is not on master branch.
Updating /home/yonsy/.pyenv/plugins/pyenv-doctor...
From https://github.com/yyuu/pyenv-doctor
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating /home/yonsy/.pyenv/plugins/pyenv-installer...
From https://github.com/yyuu/pyenv-installer
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating /home/yonsy/.pyenv/plugins/pyenv-update...
From https://github.com/yyuu/pyenv-update
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating /home/yonsy/.pyenv/plugins/pyenv-virtualenv...
From https://github.com/yyuu/pyenv-virtualenv
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating /home/yonsy/.pyenv/plugins/pyenv-which-ext...
From https://github.com/yyuu/pyenv-which-ext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
 ✘  ~ 
```

you can view the error message `pyenv-update: /home/yonsy/.pyenv is not on master branch.`

debugging this, i find that in `verify_repo_branch` function for base `~/.pyenv` directory (the pyenv repo, not plugins), `git name-rev --name-only HEAD` returns `tags/v1.0.5`, not `master` and this causes the problem.

**Comment by obestwalter** [comment]
How did you install it?

**Comment by ysolis** [comment]
tried with:

`curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash`

and

`curl pyenv.run | bash`

with both ones the problem happens again and again :)

**Comment by obestwalter** [comment]
o.k. that is strange as the first method is the recommended way and if this would be a common problem we would hear more about it here, I guess. So is there anything special about your system. Can you give a few more details?

**Comment by obestwalter** [comment]
> I have an error message that didn't appear in previous installs.

@ysolis would be great if you could nail down exactly with which change the problem was introduced.

**Comment by ysolis** [comment]
ok, previously I install pyenv in two laptops, with Archlinux and Ubuntu 14.04 LTS one and half year ago. Now this is a new laptop, With Ubuntu 16.04 LTS. I copy first .pyenv from a previous backup from $HOME from my older laptop and works well. I did must reinstall Ubuntu 16.04.1 LTS and I try the install, not deploy from my backup, and this present this problem.

**Comment by obestwalter** [comment]
I just tested it in the vagrant image that is part of this project (based on 14.04 LTS) and all looks well. Will repeat it with 16.04 LTS next ...

    vagrant@vagrant-ubuntu-trusty-64:~$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  2099  100  2099    0     0   4824      0 --:--:-- --:--:-- --:--:--  4836
    Cloning into '/home/vagrant/.pyenv'...
    remote: Counting objects: 546, done.
    remote: Compressing objects: 100% (424/424), done.
    remote: Total 546 (delta 212), reused 248 (delta 38), pack-reused 0
    Receiving objects: 100% (546/546), 245.84 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (212/212), done.
    Checking connectivity... done.
    Cloning into '/home/vagrant/.pyenv/plugins/pyenv-doctor'...
    remote: Counting objects: 11, done.
    remote: Compressing objects: 100% (8/8), done.
    remote: Total 11 (delta 1), reused 6 (delta 1), pack-reused 0
    Unpacking objects: 100% (11/11), done.
    Checking connectivity... done.
    Cloning into '/home/vagrant/.pyenv/plugins/pyenv-installer'...
    remote: Counting objects: 17, done.
    remote: Compressing objects: 100% (15/15), done.
    remote: Total 17 (delta 2), reused 10 (delta 0), pack-reused 0
    Unpacking objects: 100% (17/17), done.
    Checking connectivity... done.
    Cloning into '/home/vagrant/.pyenv/plugins/pyenv-update'...
    remote: Counting objects: 7, done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 7 (delta 1), reused 5 (delta 1), pack-reused 0
    Unpacking objects: 100% (7/7), done.
    Checking connectivity... done.
    Cloning into '/home/vagrant/.pyenv/plugins/pyenv-virtualenv'...
    remote: Counting objects: 54, done.
    remote: Compressing objects: 100% (48/48), done.
    remote: Total 54 (delta 11), reused 16 (delta 0), pack-reused 0
    Unpacking objects: 100% (54/54), done.
    Checking connectivity... done.
    Cloning into '/home/vagrant/.pyenv/plugins/pyenv-which-ext'...
    remote: Counting objects: 10, done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 10 (delta 1), reused 5 (delta 0), pack-reused 0
    Unpacking objects: 100% (10/10), done.
    Checking connectivity... done.

    WARNING: seems you still have not added 'pyenv' to the load path.

    # Load pyenv automatically by adding
    # the following to ~/.bash_profile:

    export PATH="/home/vagrant/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    vagrant@vagrant-ubuntu-trusty-64:~$ export PATH="/home/vagrant/.pyenv/bin:$PATH"
    vagrant@vagrant-ubuntu-trusty-64:~$ eval "$(pyenv init -)"
    vagrant@vagrant-ubuntu-trusty-64:~$ eval "$(pyenv virtualenv-init -)"
    vagrant@vagrant-ubuntu-trusty-64:~$ pyenv -v
    pyenv 1.0.5
    vagrant@vagrant-ubuntu-trusty-64:~$ pyenv update
    Updating /home/vagrant/.pyenv...
    From https://github.com/yyuu/pyenv
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/vagrant/.pyenv/plugins/pyenv-doctor...
    From https://github.com/yyuu/pyenv-doctor
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/vagrant/.pyenv/plugins/pyenv-installer...
    From https://github.com/yyuu/pyenv-installer
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/vagrant/.pyenv/plugins/pyenv-update...
    From https://github.com/yyuu/pyenv-update
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/vagrant/.pyenv/plugins/pyenv-virtualenv...
    From https://github.com/yyuu/pyenv-virtualenv
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/vagrant/.pyenv/plugins/pyenv-which-ext...
    From https://github.com/yyuu/pyenv-which-ext
     * branch            master     -> FETCH_HEAD
    Already up-to-date.

**Comment by obestwalter** [comment]
Same with xenial:

    15:00:33 oliver@ob1 [0] < ~/work/my_github/pyenv-installer >  1737 %
    vagrant ssh                            (git)-[pyenv-installer/master:19b1ba86c9ff! ]
    Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)

     * Documentation:  https://help.ubuntu.com
     * Management:     https://landscape.canonical.com
     * Support:        https://ubuntu.com/advantage

      Get cloud support with Ubuntu Advantage Cloud Guest:
        http://www.ubuntu.com/business/services/cloud

    0 packages can be updated.
    0 updates are security updates.


    ubuntu@ubuntu-xenial:~$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  2099  100  2099    0     0   6141      0 --:--:-- --:--:-- --:--:--  6155
    Cloning into '/home/ubuntu/.pyenv'...
    remote: Counting objects: 546, done.
    remote: Compressing objects: 100% (424/424), done.
    remote: Total 546 (delta 212), reused 248 (delta 38), pack-reused 0
    Receiving objects: 100% (546/546), 245.84 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (212/212), done.
    Checking connectivity... done.
    Cloning into '/home/ubuntu/.pyenv/plugins/pyenv-doctor'...
    remote: Counting objects: 11, done.
    remote: Compressing objects: 100% (8/8), done.
    remote: Total 11 (delta 1), reused 6 (delta 1), pack-reused 0
    Unpacking objects: 100% (11/11), done.
    Checking connectivity... done.
    Cloning into '/home/ubuntu/.pyenv/plugins/pyenv-installer'...
    remote: Counting objects: 17, done.
    remote: Compressing objects: 100% (15/15), done.
    remote: Total 17 (delta 2), reused 10 (delta 0), pack-reused 0
    Unpacking objects: 100% (17/17), done.
    Checking connectivity... done.
    Cloning into '/home/ubuntu/.pyenv/plugins/pyenv-update'...
    remote: Counting objects: 7, done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 7 (delta 1), reused 5 (delta 1), pack-reused 0
    Unpacking objects: 100% (7/7), done.
    Checking connectivity... done.
    Cloning into '/home/ubuntu/.pyenv/plugins/pyenv-virtualenv'...
    remote: Counting objects: 54, done.
    remote: Compressing objects: 100% (48/48), done.
    remote: Total 54 (delta 11), reused 16 (delta 0), pack-reused 0
    Unpacking objects: 100% (54/54), done.
    Checking connectivity... done.
    Cloning into '/home/ubuntu/.pyenv/plugins/pyenv-which-ext'...
    remote: Counting objects: 10, done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 10 (delta 1), reused 5 (delta 0), pack-reused 0
    Unpacking objects: 100% (10/10), done.
    Checking connectivity... done.

    WARNING: seems you still have not added 'pyenv' to the load path.

    # Load pyenv automatically by adding
    # the following to ~/.bash_profile:

    export PATH="/home/ubuntu/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    ubuntu@ubuntu-xenial:~$ whoami
    ubuntu
    ubuntu@ubuntu-xenial:~$ export PATH="/home/ubuntu/.pyenv/bin:$PATH"
    ubuntu@ubuntu-xenial:~$ eval "$(pyenv init -)"
    ubuntu@ubuntu-xenial:~$ eval "$(pyenv virtualenv-init -)"
    ubuntu@ubuntu-xenial:~$ pyenv -v
    pyenv 1.0.5
    ubuntu@ubuntu-xenial:~$ pyenv update
    Updating /home/ubuntu/.pyenv...
    From https://github.com/yyuu/pyenv
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/ubuntu/.pyenv/plugins/pyenv-doctor...
    From https://github.com/yyuu/pyenv-doctor
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/ubuntu/.pyenv/plugins/pyenv-installer...
    From https://github.com/yyuu/pyenv-installer
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/ubuntu/.pyenv/plugins/pyenv-update...
    From https://github.com/yyuu/pyenv-update
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/ubuntu/.pyenv/plugins/pyenv-virtualenv...
    From https://github.com/yyuu/pyenv-virtualenv
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    Updating /home/ubuntu/.pyenv/plugins/pyenv-which-ext...
    From https://github.com/yyuu/pyenv-which-ext
     * branch            master     -> FETCH_HEAD
    Already up-to-date.

**Comment by yyuu** [comment]
'pyenv update' will give up pulling the latest revision if the local repo isn't on master branch. If you want to update pyenv and plugins by the command, you meed to checkout master branch on all your local repos.

Anyway that's all implemented in https://github.com/yyuu/pyenv-update, not this project.

**Comment by ysolis** [comment]
ok, noted, resolved by me. Maybe this will be need to be an update in the documentation or for pyenv-update ?

**Comment by dieggsy** [comment]
@ysolis i'm now getting this error too. How'd you resolve it?
