### ISSUE TITLE
unable to install pyenv on windows 10 (pip install pyenv )

### ISSUE THREAD

**Issue by nikesh363** [yyuu/pyenv-installer#47]
Collecting pyenv
  Using cached pyenv-20150113.1.tar.gz
Building wheels for collected packages: pyenv
  Running setup.py bdist_wheel for pyenv ... error
  Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-build-6ldgff\\pyenv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\user\appdata\local\temp\tmprauu_6pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  installing to build\bdist.win32\wheel
  running install
  error: [Error 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for pyenv
  Running setup.py clean for pyenv
Failed to build pyenv
Installing collected packages: pyenv
  Running setup.py install for pyenv ... error
    Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-build-6ldgff\\pyenv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-wg9dun-record\install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-build-6ldgff\\pyenv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-wg9dun-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-build-6ldgff\pyenv\

**Comment by obestwalter** [comment]
Hi, sorry but pyenv ist not supported on Windows and likely isn't if nobody takes that in their own hands. See: https://github.com/yyuu/pyenv/issues/62.

**Comment by yyuu** [comment]
I guess pyenv could be able to work on bash on Windows. I've never tried, though.

Anyway it seems the error is occurring inside setuptools or pip, not in pyenv's code.

**Comment by obestwalter** [comment]
> Anyway it seems the error is occurring inside setuptools or pip, not in pyenv's code.

That's the other thing ... I will definitely have to carve out some time to make it work consistently with the pip installer (see: https://github.com/yyuu/pyenv-installer/issues/25) or admit defeat and propse complete removal of the installer (but then we have a project on pypi that is not pip installable - bad).

**Comment by fenchu** [comment]
pyenv works excellent under windows subsystem for linux, but You need windows10anniversary edition or newer.

**Comment by darkn3rd** [comment]
If you use a python in one of these environments, such as CygWin and especially WSL, you will have limited integration with other tools that require python.  The recommendation out there, is to use conda tool to manage versions.  I'm still testing this out, for compatibility with tools like node-gyp that many Node NPM packages use.

**Comment by Arkelis** [comment]
@nikesh363 See [pyenv-win](https://github.com/pyenv-win/pyenv-win) by [kirankotari](https://github.com/kirankotari) for a Windows port.
