### ISSUE TITLE
Define what "friends" means exactly?

### ISSUE THREAD

**Issue by Ivoz** [yyuu/pyenv-installer#5]
Also, does this script do things automatically as soon as you run it, or does it ask some questions, give you time to cancel?

Can it just install `pyenv`, or does it always install its "friends" with it?

This stuff would be nice to know in the readme before being asked to just run something in your shell.

**Comment by yyuu** [comment]
The _friends_ here means "plugins I am using conveniently". Anyone can fork and maintain their forks if they want to do differently.

**Comment by xpe** [comment]
^ Would you please add your definition of friends to the README?
