### ISSUE TITLE
pyenv update no such command

### ISSUE THREAD

**Issue by elcolie** [yyuu/pyenv-installer#50]
OSX: 10.12.2
pyenv: 1.0.6
```
(cdm-ops-web) Sarits-MacBook-Air-2:cdm-ops-web el$ pyenv update
pyenv: no such command `update'

(cdm-ops-web) Sarits-MacBook-Air-2:cdm-ops-web el$ cat ~/.bash_profile
# pyenv
export PATH="/Users/el/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

Is `pyenv update` valid on OSX 10.12.2?

**Comment by obestwalter** [comment]
Hi @elcolie,

> Is pyenv update valid on OSX 10.12.2?

I am not on Mac myself, so I am not sure and maybe it depends how you installed it. pyenv update is not part of the core, but it is a [plugin](https://github.com/yyuu/pyenv-update) that at least on Linux is part of the normal install. But maybe this is different if you installed through homebrew, which then might have it's own update mechanism, but I am really guessing here.

So, can you tell us how you installed it (homebrew or script ... please not pip - see https://github.com/yyuu/pyenv-installer/issues/43#issuecomment-261276994)? Did you have any problems or errors while installing? What does your pyenv/plugins folder look like? If you installed via shell script and, I would hazard a guess that `pyenv-update` folder is missing/corrupt.

**Comment by elcolie** [comment]
@obestwalter Thank you for pointing out. I read the wrong source.
I have to use
```
brew update
brew upgrade
```
To get the latest version of `pyenv`
Thank you very much
