### ISSUE TITLE
potentially missing symlink

### ISSUE THREAD

**Issue by mkassner** [yyuu/pyenv-installer#52]
For compiling opencv and python-boost against a pyen python I had to add the following link:

 `~/.pyenv/versions/{envname}/include/python3.6` 
pointing to
` ~/.pyenv/versions/3.6.0/include/python3.6.m` 

I think this should be added by default.

**Comment by obestwalter** [comment]
Thanks for reproting this @mkassner, but I doubt that this is an issue for the installer. If a symlink that should be created during virtualenv creation is missing, I would guess that this belongs to [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) or in doubt the main project [pyenv](https://github.com/yyuu/pyenv). If you know your way around bash: maybe you could check the code where the symlinking is done and open a PR against the affected project?

**Comment by mkassner** [comment]
moved to https://github.com/yyuu/pyenv-virtualenv/issues/200

Thank you!
